version: 2.1
orbs:
  kubernetes: circleci/kubernetes@0.11.2
  aws-eks: circleci/aws-eks@0.2.0
  aws-ecr: circleci/aws-ecr@3.1.0

jobs:
  build:
    executor: aws-eks/python3
    steps:
      - checkout
      - kubernetes/install-kubectl
      - kubernetes/install-kubeconfig
      - run:
          name: jhj
          command: echo ${KUBECONFIG_DATA}
workflows:
  build-test:
    jobs:
      - build
