version: 2.1
orbs:
  kubernetes: circleci/kubernetes@0.11.2
  aws-eks: circleci/aws-eks@0.2.0
  aws-ecr: circleci/aws-ecr@3.1.0

jobs:
  build:
    executor: aws-eks/python3
    steps:
      - checkout
      - kubernetes/install-kubectl
      - kubernetes/install-kubeconfig
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: revo_test
          install-kubectl: true
          aws-region: eu-west-2
      - run:
          name: hg
          command: kubectl get nodes
workflows:
  build-test:
    jobs:
      - build
#./mvnw clean install jib:build -Djib.to.auth.username=$DOCKER_USERNAME -Djib.to.auth.password=$DOCKER_PASSWORD -Dbuild.number=RestAPIBi
